### ISSUE TITLE
/Index can not be displayed

### ISSUE THREAD

**Issue by SnipeLike** [Rhilip/RidPT#10]
I am trying to run ridpt in a docker container unsing LEMP with external DB.
So far I was able to run the page and register a new account. 
But after the Login, the page redirects me to /Index (gues login worked) and then the Index page can not be reached ("This site cant be reached"). Sometimes the whole container crashes trying to access this page.

**Ridpt.log**:
`192.168.1.181 - - [11/Feb/2020:14:35:40 +0000] "POST /auth/register HTTP/1.1" 302 0 "http://192.168.2.10:880/auth/register" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.94 Safari/537.36"
192.168.1.181 - - [11/Feb/2020:14:35:40 +0000] "GET /index HTTP/1.1" 302 0 "http://192.168.2.10:880/auth/register" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.94 Safari/537.36"
192.168.1.181 - - [11/Feb/2020:14:35:40 +0000] "GET /auth/login HTTP/1.1" 200 2569 "http://192.168.2.10:880/auth/register" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.94 Safari/537.36"
192.168.1.181 - - [11/Feb/2020:14:36:00 +0000] "POST /auth/login HTTP/1.1" 302 0 "http://192.168.2.10:880/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.94 Safari/537.36"
192.168.1.181 - - [11/Feb/2020:14:36:01 +0000] "GET /index HTTP/1.1" 302 3592 "http://192.168.2.10:880/auth/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.94 Safari/537.36"`

**Versions**:
System      Name:      Linux
Framework   Version:   v0.1.6-alpha
PHP         Version:   7.4.0
Swoole      Version:   4.4.12
Listen      Addr:      127.0.0.1
Port:      9501
Num:       1
Num:       5
Hot         Update:    enabled
Coroutine   Mode:      disabled
Config      File:      /var/www/html/config/application.php
Nginx 1.16.1

**Comment by Rhilip** [comment]
I'm sorry, and fix it in 82977ea4b86053f797d45d684599ab97806ffbb2 with reason in this comment words.

**Comment by SnipeLike** [comment]
Unfortunately even with the changes in 82977ea (Response.php) this error still occurs in my setup.
